baseURL = '/'
languageCode = 'en-us'
title = "jzbors's Homepage"

theme = 'terminal'

[params]
  themeColor = "blue"
  centerTheme = true

[languages]
  [languages.en]
    # [[languages.en.menu.main]]
    #   identifier = "posts"
    #   name = "Posts"
    #   url = "/posts"
