baseURL = '/'
languageCode = 'en-us'
title = "jzbors's Homepage"

theme = 'terminal-justinnuwin'

[params]
themeColor = "orange"
centerTheme = true
fullWidthTheme = false
singlePageSite = true

[languages.en]
title = "/home/jzbor"
#subtitle = "jzbor's Homepage"
keywords = ""
copyright = "© 2023 jzbor"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "/home/jzbor"

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/#about"
weight = 1

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 2
